services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    #   POSTGRES_DB: odoo
    # volumes:
    #   - ./docker/postgres:/var/lib/postgresql/data
